### ISSUE TITLE
Prepare code for Stepper and Servo Motors

### ISSUE THREAD

**Issue by abhishekd-1** [RoboManipal-9-0/Coding-Task-Phase#1]
### Task description
- [ ] Code for Servo to move it to a certain degree.
- [ ] Code to take user input and move Servo to that certain degree.
- [ ] Code to move a Stepper to a certain degree

### Extras
- [ ] Complete Testing on Arduino
